#
# Configuration for environment
#
version: 1.0
app:
  # build id to deploy. if 'version' is commented out, the application is not deployed

  version: ""
  # version: ""
  
  # number of instances
  instances:
    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    max: 1
    
  resources:
    # max cpu. memory limit is based on cpu value: 1:4 memory ratio, e.g. 1 cpu == 4 gb
    cpu: 1
  java: 8

  # To get an external URL to access the application
  endpoints: public
  
  # List of environment variables that are set for the application
  env:
    - name: qs.security.username
      value: admin
    - name: app.gsdb.name
      value: GSDB
    - name: app.gsdb.hostname
      value: easej-svt-vm.purple-mystic-butterfly.com
    - name: app.gsdb.port
      value: "60015"
    - name: app.gsdb.user
      value: db2inst1
    - name: app.ccdb.name
      value: CCDB
    - name: app.ccdb.hostname
      value: easej-svt-vm.purple-mystic-butterfly.com
    - name: app.ccdb.port
      value: "60015"
    - name: app.ccdb.user
      value: db2inst1
    - name: app.ccdb.name
      value: CCDB
    - name: app.ccdb.hostname
      value: easej-svt-vm.purple-mystic-butterfly.com
    - name: app.ccdb.port
      value: "60015"
    - name: app.ccdb.user
      value: db2inst1

  # List of variables that can be referenced in the server.xml
  #variables:
  #  - name: discoveryEndpoint
  #    value: "https://rhaque-12022024.verify.ibm.com/oidc/endpoint/default/.well-known/openid-configuration"
  #  - name: clientId
  #    value: "cf2ff435-a353-4e74-b383-986c23dddd2f"